# Change these first
owner: nexusnotes # Your GitHub username
repo: upptime # Your GitHub repository name

user-agent: vaughansharman

# Add your sites here
sites:
  - name: Nexus Notes
    url: https://nexusnotes.com
  - name: Nexus Notes Members
    url: https://members.nexusnotes.com

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Nexus Notes** Uptime Statistics."
  introMessage: This is a status page with **real-time** uptime data
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees: # Users to assign downtime issues (optional)
  - vaughansharman

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
